// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yggdrasil.Data;

#nullable disable

namespace Yggdrasil_ai_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007054520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Yggdrasil.Models.Character", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Appearance")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Conversation_ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExampleDialogue")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NarrativeRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronouns")
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorldID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("WorldID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.Prompt", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SystemPromptID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SystemPromptID");

                    b.ToTable("Prompt");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.Settings", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivePromptID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefaultPromptID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ActivePromptID");

                    b.HasIndex("DefaultPromptID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.SystemPrompt", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SystemPrompt");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.World", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Lorebook_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("NarratorExampleDialogue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NarratorInstruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("World");
                });

            modelBuilder.Entity("Yggdrasil.Models.Character", b =>
                {
                    b.HasOne("Yggdrasil.Models.Entities.World", null)
                        .WithMany("Characters")
                        .HasForeignKey("WorldID");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.Prompt", b =>
                {
                    b.HasOne("Yggdrasil.Models.Entities.SystemPrompt", null)
                        .WithMany("Prompts")
                        .HasForeignKey("SystemPromptID");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.Settings", b =>
                {
                    b.HasOne("Yggdrasil.Models.Entities.SystemPrompt", "ActivePrompt")
                        .WithMany()
                        .HasForeignKey("ActivePromptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Models.Entities.SystemPrompt", "DefaultPrompt")
                        .WithMany()
                        .HasForeignKey("DefaultPromptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePrompt");

                    b.Navigation("DefaultPrompt");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.SystemPrompt", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Yggdrasil.Models.Entities.World", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
